services:
  cache:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data

  db:
    image: postgres:16.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=musicbrainz
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  dragonflydata:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /srv/dragonflydb
      o: bind
  db:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /srv/postgres
      o: bind
